2019-12-14 14:26:45,912 ERROR: Exception on /explore [GET] [in c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Uczelnia\microblog\app\routes.py", line 57, in explore
    next_url=next_url, prev_url=prev_url)
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\uczelnia\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\uczelnia\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\uczelnia\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\uczelnia\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Uczelnia\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Uczelnia\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\uczelnia\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Uczelnia\microblog\app\templates\base.html", line 56, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Uczelnia\microblog\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Uczelnia\microblog\app\templates\_post.html", line 18, in top-level template code
    <br>
jinja2.exceptions.UndefinedError: 'print' is undefined
2019-12-14 14:28:58,084 INFO: Microblog startup [in C:\Uczelnia\microblog\app\__init__.py:56]
2019-12-14 19:08:46,919 INFO: Microblog startup [in C:\Uczelnia\microblog\app\__init__.py:59]
2019-12-14 19:26:17,455 INFO: Microblog startup [in C:\Uczelnia\microblog\app\__init__.py:59]
